version: '3.4'
services:
    fluentd:
        build: ./dockerfile/fluentd
        expose:
            - 5140
        ports:
            - 5140:5140
            - 24224:24224
            - 2056:2056
        environment:
            - 'FLUENTD_CONF=fluentd.conf'
        volumes:
            - ./fluentd/etc/fluentd.conf:/fluentd/etc/fluentd.conf:ro

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
        container_name: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - data:/usr/share/elasticsearch/data
        depends_on:
            - fluentd

    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.1
        container_name: kibana
        environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9200"
        ports:
            - 5601:5601
        links:
            - elasticsearch
        restart: always
        depends_on:
            - elasticsearch

volumes:
  data:
    driver: 'local'
