version: '3.3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
        container_name: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
        volumes:
            - data:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:7.3.0
        container_name: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch
        restart: always
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200

volumes:
  data:
    driver: 'local'
