version: '3'
services:
  zabbix_server:
    image: zabbix/zabbix-server-mysql:alpine-4.0-latest
    ports:
      - "10051:10051"
      - "161:161"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_SERVER_HOST=zabbix_db
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - ZBX_DEBUGLEVEL=${LOG_LEVEL}
    links:
      - zabbix_db


  zabbix_web_apache_mysql:
    image: zabbix/zabbix-web-apache-mysql:alpine-4.0-latest
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZBX_SERVER_HOST=zabbix_server
      - DB_SERVER_HOST=zabbix_db
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - PHP_TZ=${TIME_ZONE}
    links:
      - zabbix_server
      - zabbix_db


  zabbix_agent:
    image: zabbix/zabbix-agent:alpine-4.0-latest
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZBX_SERVER_HOST=zabbix_server
    privileged: true
    links:
      - zabbix_server

  zabbix_db:
    image: mysql:5.7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
