version: "3"
services:
  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    container_name: influxdb
    volumes:
      - ./influxdb:/data
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app,grafana-piechart-panel
      GF_SERVER_ROOT_URL: http://yourdomain/grafana/
      GF_SECURITY_ADMIN_USER: user 
      GF_SECURITY_ADMIN_PASSWORD: password
      VIRTUAL_HOST: log.yoneyan.net/grafana
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always
