name: fluentd-dockerimage

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
       cd ./kibana/dockerfile/fluentd
       docker build . --tag my-image-name:$(date +%s)
